# Generated by Django 5.1.5 on 2025-02-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True)),
                ('device_type', models.CharField(choices=[('Router', 'Router'), ('Switch', 'Switch'), ('Firewall', 'Firewall'), ('Server', 'Server')], max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
